set up # vim:set ts=8 sts=2 sw=2 et: or ease of reading

diff --git a/pulseaudio-ctl b/pulseaudio-ctl
--- a/pulseaudio-ctl
+++ b/pulseaudio-ctl
@@ -26,52 +26,54 @@ echo "I require pactl but it's not installed. Aborting." >&2
 exit 1; }
 
 setup() {
-	SINK=$(pacmd list-sinks|awk '/* index:/{ print $3 }')
-	MUTED=$(pacmd list-sinks|grep -A 15 '* index'|awk '/muted:/{ print $2 }')
-	CURVOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: 0:/{ print $3 }'|sed 's/%//')
+  SINK=$(pacmd list-sinks|awk '/* index:/{ print $3 }')
+  MUTED=$(pacmd list-sinks|grep -A 15 '* index'|awk '/muted:/{ print $2 }')
+  CURVOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: 0:/{ print $3 }'|sed 's/%//')
 
-	if [ "$CURVOL" -ge 0 -o "$CURVOL" -lt 0 2>/dev/null ]; then
-		return 0
-	else
-		# the git snapshot at the time of writing this script changes the
-		# expected output of this cmd
-		CURVOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: front/{ print $5 }' | sed 's/%//g')
-		if [ "$CURVOL" -ge 0 -o "$CURVOL" -lt 0 2>/dev/null ]; then
-			return 0
-		else
-			echo -e " ${BLD}${RED}Cannot find current volume. CURVOL = ${CURVOL}${NRM}"
-			exit 1
-		fi
-	fi
+  if [ "$CURVOL" -ge 0 -o "$CURVOL" -lt 0 2>/dev/null ]; then
+    return 0
+  else
+    # the git snapshot at the time of writing this script changes the
+    # expected output of this cmd
+    CURVOL=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: front/{ print $5 }' | sed 's/%//g')
+    if [ "$CURVOL" -ge 0 -o "$CURVOL" -lt 0 2>/dev/null ]; then
+      return 0
+    else
+      echo -e " ${BLD}${RED}Cannot find current volume. CURVOL = ${CURVOL}${NRM}"
+      exit 1
+    fi
+  fi
 }
 
 case "$1" in
-	U|u|[U,u]p)
-		# raise volume by 5%
-		setup
-		[[ "$CURVOL" -ge 100 ]] && exit 0 ||
-			pactl set-sink-volume "$SINK" -- +5%
-		;;
-	D|d|[D,d]own|[D,d]o)
-		# lowers volume by 5%
-		setup
-		[[ "$CURVOL" -le 0 ]] && exit 0 ||
-			pactl set-sink-volume "$SINK" -- -5%
-		;;
-	M|m|[M,m]u|[M,m]ute)
-		# mutes the volume entirely
-		setup
-		pactl set-sink-mute "$SINK" toggle
-		;;
-	*)
-		setup
-		echo -e " ${BLD}$0 ${NRM}${BLU}{up,down,mute}${NRM}"
-		echo
-		echo -e " ${BLD}Where ${NRM}${BLU}up${NRM}${BLD} and ${NRM}${BLU}down${NRM}${BLD} adjust volume in ±5 % increments.${NRM}"
-		echo -e " ${BLD}Where ${NRM}${BLU}mute${NRM}${BLD} toggles the mute status on/off.${NRM}"
-		echo
-		echo -e " ${BLD}Volume level  : ${NRM}${RED}$CURVOL %${NRM}"
-		echo -e " ${BLD}Is sink muted : ${NRM}${RED}$MUTED${NRM}"
-		exit 0
-		;;
+  U|u|[U,u]p)
+    # raise volume by 5%
+    setup
+    [[ "$CURVOL" -ge 100 ]] && exit 0 ||
+      pactl set-sink-volume "$SINK" -- +5%
+    ;;
+  D|d|[D,d]own|[D,d]o)
+    # lowers volume by 5%
+    setup
+    [[ "$CURVOL" -le 0 ]] && exit 0 ||
+      pactl set-sink-volume "$SINK" -- -5%
+    ;;
+  M|m|[M,m]u|[M,m]ute)
+    # mutes the volume entirely
+    setup
+    pactl set-sink-mute "$SINK" toggle
+    ;;
+  *)
+    setup
+    echo -e " ${BLD}$0 ${NRM}${BLU}{up,down,mute}${NRM}"
+    echo
+    echo -e " ${BLD}Where ${NRM}${BLU}up${NRM}${BLD} and ${NRM}${BLU}down${NRM}${BLD} adjust volume in ±5 % increments.${NRM}"
+    echo -e " ${BLD}Where ${NRM}${BLU}mute${NRM}${BLD} toggles the mute status on/off.${NRM}"
+    echo
+    echo -e " ${BLD}Volume level  : ${NRM}${RED}$CURVOL %${NRM}"
+    echo -e " ${BLD}Is sink muted : ${NRM}${RED}$MUTED${NRM}"
+    exit 0
+    ;;
 esac
+
+# vim:set ts=8 sts=2 sw=2 et:
