initial support for libnotify

diff --git a/common/pulseaudio-ctl.in b/common/pulseaudio-ctl.in
--- a/common/pulseaudio-ctl.in
+++ b/common/pulseaudio-ctl.in
@@ -65,6 +65,14 @@ checkconfig() {
       UPPER_THRESHOLD=100
     fi
   fi
+  
+  if [[ -n "$NOTIFY" ]]; then
+    command -v notify-send >/dev/null 2>&1 || {
+    echo "You wish to use notifications but I require notify-send but it's not installed." >&2
+    echo "Modify $CONFIG or install the package that provides it. Aborting." >&2
+    exit 1; }
+    export "$NOTIFY"
+  fi
 }
 
 setup() {
@@ -101,25 +109,32 @@ case "$1" in
     # in cases where external apps have pushed it above
     [[ "$CURVOL" -ge $UPPER_THRESHOLD ]] && pactl set-sink-volume "$SINK" $UPPER_THRESHOLD% ||
       pactl set-sink-volume "$SINK" -- +5%
+    [[ -n "$NOTIFY" ]] && notify-send -t 1000 --hint=int:transient:1 "volume up" "level: $CURVOL"
     ;;
   D|d|[D,d]own|[D,d]o)
     # lowers volume by 5%
     [[ "$CURVOL" -le 0 ]] && exit 0 ||
       pactl set-sink-volume "$SINK" -- -5%
+    [[ -n "$NOTIFY" ]] && notify-send -t 1000 --hint=int:transient:1 "volume down" "level: $CURVOL"
     ;;
   M|m|[M,m]u|[M,m]ute)
     # mutes the volume entirely
     pactl set-sink-mute "$SINK" toggle
+    MUTED=$(pacmd list-sinks|grep -A 15 '* index'|awk '/muted:/{ print $2 }')
+    [[ -n "$NOTIFY" ]] && notify-send -t 1000 --hint=int:transient:1 "mute toggle" "muted: $MUTED"
     ;;
   [M,m]i|[M,m]ute-[I,i]nput)
     # mutes the microphone entirely
     pactl set-source-mute "$SOURCE" toggle
+    SOURCE_MUTED=$(pacmd list-sources|grep -A 15 '* index'|awk '/muted:/{ print $2 }')
+    [[ -n "$NOTIFY" ]] && notify-send -t 1000 --hint=int:transient:1 "mute toggle" "muted: $SOURCE_MUTED"
     ;;
   set)
     NEWVOL="${2%%%}"
     [[ "$NEWVOL" -ge $UPPER_THRESHOLD ]] && exit 0 ||
       [[ "$NEWVOL" -le 0 ]] && exit 0 ||
       pactl set-sink-volume "$SINK" -- $NEWVOL%
+    [[ -n "$NOTIFY" ]] && notify-send -t 1000 --hint=int:transient:1 "volume set" "level: $CURVOL"
     ;;
   atmost)
     NEWVOL="${2%%%}"
@@ -127,6 +142,7 @@ case "$1" in
       [[ "$NEWVOL" -ge $UPPER_THRESHOLD ]] && exit 0 ||
       [[ "$NEWVOL" -le 0 ]] && exit 0 ||
       pactl set-sink-volume "$SINK" -- $NEWVOL%
+    [[ -n "$NOTIFY" ]] && notify-send -t 1000 --hint=int:transient:1 "atmost set" "level: $CURVOL"
     ;;
   *)
     echo -e "${BLD}pulseaudio-ctl v$VERS${NRM}"
