Fixed error messages for missing programs

diff --git a/common/pulseaudio-ctl.in b/common/pulseaudio-ctl.in
--- a/common/pulseaudio-ctl.in
+++ b/common/pulseaudio-ctl.in
@@ -23,11 +23,11 @@ echo "I require sed but it's not installed. Aborting." >&2
 exit 1; }
 
 command -v grep >/dev/null 2>&1 || {
-echo "I require sed but it's not installed. Aborting." >&2
+echo "I require grep but it's not installed. Aborting." >&2
 exit 1; }
 
 command -v cut >/dev/null 2>&1 || {
-echo "I require sed but it's not installed. Aborting." >&2
+echo "I require cut but it's not installed. Aborting." >&2
 exit 1; }
 
 command -v awk >/dev/null 2>&1 || {
